import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c7c4d8",
        "surface-variant": "#dae2fd",
        "tertiary": "#3a495f",
        "surface-tint": "#4d44e3",
        "primary-fixed": "#e2dfff",
        "surface-bright": "#faf8ff",
        "secondary": "#006c49",
        "on-tertiary-fixed": "#0b1c30",
        "inverse-on-surface": "#eef0ff",
        "on-primary-container": "#dad7ff",
        "inverse-surface": "#283044",
        "on-error": "#ffffff",
        "on-background": "#131b2e",
        "secondary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container-low": "#f2f3ff",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#c3c0ff",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#002113",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#c3c0ff",
        "on-secondary-container": "#00714d",
        "surface-container": "#eaedff",
        "outline": "#777587",
        "on-primary": "#ffffff",
        "on-surface": "#131b2e",
        "primary": "#3525cd",
        "background": "#faf8ff",
        "secondary-container": "#6cf8bb",
        "surface": "#faf8ff",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-highest": "#dae2fd",
        "surface-dim": "#d2d9f4",
        "on-tertiary-fixed-variant": "#38485d",
        "tertiary-fixed": "#d3e4fe",
        "tertiary-container": "#516177",
        "primary-container": "#4f46e5",
        "on-surface-variant": "#464555",
        "on-tertiary-container": "#ccdcf7",
        "on-primary-fixed": "#0f0069",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "surface-container-high": "#e2e7ff",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "margin": "2rem",
      },
    },
  },
  plugins: [],
};

export default config;
